//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	redirection "k8s.io/kubernetes/pkg/extendedapis/redirection"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*RedirectionCheckConfiguration)(nil), (*redirection.RedirectionCheckConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RedirectionCheckConfiguration_To_redirection_RedirectionCheckConfiguration(a.(*RedirectionCheckConfiguration), b.(*redirection.RedirectionCheckConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*redirection.RedirectionCheckConfiguration)(nil), (*RedirectionCheckConfiguration)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_redirection_RedirectionCheckConfiguration_To_v1_RedirectionCheckConfiguration(a.(*redirection.RedirectionCheckConfiguration), b.(*RedirectionCheckConfiguration), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RedirectionCheckConfigurationList)(nil), (*redirection.RedirectionCheckConfigurationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RedirectionCheckConfigurationList_To_redirection_RedirectionCheckConfigurationList(a.(*RedirectionCheckConfigurationList), b.(*redirection.RedirectionCheckConfigurationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*redirection.RedirectionCheckConfigurationList)(nil), (*RedirectionCheckConfigurationList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_redirection_RedirectionCheckConfigurationList_To_v1_RedirectionCheckConfigurationList(a.(*redirection.RedirectionCheckConfigurationList), b.(*RedirectionCheckConfigurationList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*RedirectionCheckSpec)(nil), (*redirection.RedirectionCheckSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1_RedirectionCheckSpec_To_redirection_RedirectionCheckSpec(a.(*RedirectionCheckSpec), b.(*redirection.RedirectionCheckSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*redirection.RedirectionCheckSpec)(nil), (*RedirectionCheckSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_redirection_RedirectionCheckSpec_To_v1_RedirectionCheckSpec(a.(*redirection.RedirectionCheckSpec), b.(*RedirectionCheckSpec), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1_RedirectionCheckConfiguration_To_redirection_RedirectionCheckConfiguration(in *RedirectionCheckConfiguration, out *redirection.RedirectionCheckConfiguration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1_RedirectionCheckSpec_To_redirection_RedirectionCheckSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1_RedirectionCheckConfiguration_To_redirection_RedirectionCheckConfiguration is an autogenerated conversion function.
func Convert_v1_RedirectionCheckConfiguration_To_redirection_RedirectionCheckConfiguration(in *RedirectionCheckConfiguration, out *redirection.RedirectionCheckConfiguration, s conversion.Scope) error {
	return autoConvert_v1_RedirectionCheckConfiguration_To_redirection_RedirectionCheckConfiguration(in, out, s)
}

func autoConvert_redirection_RedirectionCheckConfiguration_To_v1_RedirectionCheckConfiguration(in *redirection.RedirectionCheckConfiguration, out *RedirectionCheckConfiguration, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_redirection_RedirectionCheckSpec_To_v1_RedirectionCheckSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	return nil
}

// Convert_redirection_RedirectionCheckConfiguration_To_v1_RedirectionCheckConfiguration is an autogenerated conversion function.
func Convert_redirection_RedirectionCheckConfiguration_To_v1_RedirectionCheckConfiguration(in *redirection.RedirectionCheckConfiguration, out *RedirectionCheckConfiguration, s conversion.Scope) error {
	return autoConvert_redirection_RedirectionCheckConfiguration_To_v1_RedirectionCheckConfiguration(in, out, s)
}

func autoConvert_v1_RedirectionCheckConfigurationList_To_redirection_RedirectionCheckConfigurationList(in *RedirectionCheckConfigurationList, out *redirection.RedirectionCheckConfigurationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]redirection.RedirectionCheckConfiguration)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1_RedirectionCheckConfigurationList_To_redirection_RedirectionCheckConfigurationList is an autogenerated conversion function.
func Convert_v1_RedirectionCheckConfigurationList_To_redirection_RedirectionCheckConfigurationList(in *RedirectionCheckConfigurationList, out *redirection.RedirectionCheckConfigurationList, s conversion.Scope) error {
	return autoConvert_v1_RedirectionCheckConfigurationList_To_redirection_RedirectionCheckConfigurationList(in, out, s)
}

func autoConvert_redirection_RedirectionCheckConfigurationList_To_v1_RedirectionCheckConfigurationList(in *redirection.RedirectionCheckConfigurationList, out *RedirectionCheckConfigurationList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]RedirectionCheckConfiguration)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_redirection_RedirectionCheckConfigurationList_To_v1_RedirectionCheckConfigurationList is an autogenerated conversion function.
func Convert_redirection_RedirectionCheckConfigurationList_To_v1_RedirectionCheckConfigurationList(in *redirection.RedirectionCheckConfigurationList, out *RedirectionCheckConfigurationList, s conversion.Scope) error {
	return autoConvert_redirection_RedirectionCheckConfigurationList_To_v1_RedirectionCheckConfigurationList(in, out, s)
}

func autoConvert_v1_RedirectionCheckSpec_To_redirection_RedirectionCheckSpec(in *RedirectionCheckSpec, out *redirection.RedirectionCheckSpec, s conversion.Scope) error {
	out.AllowedRedirectionHosts = *(*[]string)(unsafe.Pointer(&in.AllowedRedirectionHosts))
	return nil
}

// Convert_v1_RedirectionCheckSpec_To_redirection_RedirectionCheckSpec is an autogenerated conversion function.
func Convert_v1_RedirectionCheckSpec_To_redirection_RedirectionCheckSpec(in *RedirectionCheckSpec, out *redirection.RedirectionCheckSpec, s conversion.Scope) error {
	return autoConvert_v1_RedirectionCheckSpec_To_redirection_RedirectionCheckSpec(in, out, s)
}

func autoConvert_redirection_RedirectionCheckSpec_To_v1_RedirectionCheckSpec(in *redirection.RedirectionCheckSpec, out *RedirectionCheckSpec, s conversion.Scope) error {
	out.AllowedRedirectionHosts = *(*[]string)(unsafe.Pointer(&in.AllowedRedirectionHosts))
	return nil
}

// Convert_redirection_RedirectionCheckSpec_To_v1_RedirectionCheckSpec is an autogenerated conversion function.
func Convert_redirection_RedirectionCheckSpec_To_v1_RedirectionCheckSpec(in *redirection.RedirectionCheckSpec, out *RedirectionCheckSpec, s conversion.Scope) error {
	return autoConvert_redirection_RedirectionCheckSpec_To_v1_RedirectionCheckSpec(in, out, s)
}
