/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1 "k8s.io/kubernetes/pkg/extendedapis/redirection/v1"
	redirectionv1 "k8s.io/kubernetes/pkg/extendedgenerated/applyconfiguration/redirection/v1"
)

// FakeRedirectionCheckConfigurations implements RedirectionCheckConfigurationInterface
type FakeRedirectionCheckConfigurations struct {
	Fake *FakeRedirectionV1
}

var redirectioncheckconfigurationsResource = v1.SchemeGroupVersion.WithResource("redirectioncheckconfigurations")

var redirectioncheckconfigurationsKind = v1.SchemeGroupVersion.WithKind("RedirectionCheckConfiguration")

// Get takes name of the redirectionCheckConfiguration, and returns the corresponding redirectionCheckConfiguration object, and an error if there is any.
func (c *FakeRedirectionCheckConfigurations) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.RedirectionCheckConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(redirectioncheckconfigurationsResource, name), &v1.RedirectionCheckConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RedirectionCheckConfiguration), err
}

// List takes label and field selectors, and returns the list of RedirectionCheckConfigurations that match those selectors.
func (c *FakeRedirectionCheckConfigurations) List(ctx context.Context, opts metav1.ListOptions) (result *v1.RedirectionCheckConfigurationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(redirectioncheckconfigurationsResource, redirectioncheckconfigurationsKind, opts), &v1.RedirectionCheckConfigurationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.RedirectionCheckConfigurationList{ListMeta: obj.(*v1.RedirectionCheckConfigurationList).ListMeta}
	for _, item := range obj.(*v1.RedirectionCheckConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested redirectionCheckConfigurations.
func (c *FakeRedirectionCheckConfigurations) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(redirectioncheckconfigurationsResource, opts))
}

// Create takes the representation of a redirectionCheckConfiguration and creates it.  Returns the server's representation of the redirectionCheckConfiguration, and an error, if there is any.
func (c *FakeRedirectionCheckConfigurations) Create(ctx context.Context, redirectionCheckConfiguration *v1.RedirectionCheckConfiguration, opts metav1.CreateOptions) (result *v1.RedirectionCheckConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(redirectioncheckconfigurationsResource, redirectionCheckConfiguration), &v1.RedirectionCheckConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RedirectionCheckConfiguration), err
}

// Update takes the representation of a redirectionCheckConfiguration and updates it. Returns the server's representation of the redirectionCheckConfiguration, and an error, if there is any.
func (c *FakeRedirectionCheckConfigurations) Update(ctx context.Context, redirectionCheckConfiguration *v1.RedirectionCheckConfiguration, opts metav1.UpdateOptions) (result *v1.RedirectionCheckConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(redirectioncheckconfigurationsResource, redirectionCheckConfiguration), &v1.RedirectionCheckConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RedirectionCheckConfiguration), err
}

// Delete takes name of the redirectionCheckConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeRedirectionCheckConfigurations) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteActionWithOptions(redirectioncheckconfigurationsResource, name, opts), &v1.RedirectionCheckConfiguration{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRedirectionCheckConfigurations) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(redirectioncheckconfigurationsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1.RedirectionCheckConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched redirectionCheckConfiguration.
func (c *FakeRedirectionCheckConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.RedirectionCheckConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(redirectioncheckconfigurationsResource, name, pt, data, subresources...), &v1.RedirectionCheckConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RedirectionCheckConfiguration), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied redirectionCheckConfiguration.
func (c *FakeRedirectionCheckConfigurations) Apply(ctx context.Context, redirectionCheckConfiguration *redirectionv1.RedirectionCheckConfigurationApplyConfiguration, opts metav1.ApplyOptions) (result *v1.RedirectionCheckConfiguration, err error) {
	if redirectionCheckConfiguration == nil {
		return nil, fmt.Errorf("redirectionCheckConfiguration provided to Apply must not be nil")
	}
	data, err := json.Marshal(redirectionCheckConfiguration)
	if err != nil {
		return nil, err
	}
	name := redirectionCheckConfiguration.Name
	if name == nil {
		return nil, fmt.Errorf("redirectionCheckConfiguration.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(redirectioncheckconfigurationsResource, *name, types.ApplyPatchType, data), &v1.RedirectionCheckConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1.RedirectionCheckConfiguration), err
}
